export const LOGIN_API_PENDING = 'LOGIN_API_PENDING';
export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const LOGIN_API_ERROR = 'LOGIN_API_ERROR';
export const LOGIN_RESET = 'LOGIN_RESET';

export const SIGNUP_API_PENDING = 'SIGNUP_API_PENDING';
export const SIGNUP_API_SUCCESS = 'SIGNUP_API_SUCCESS';
export const SIGNUP_API_ERROR = 'SIGNUP_API_ERROR';
export const SIGNUP_RESET = 'SIGNUP_RESET';

export const GET_ROLE_API_PENDING = 'GET_ROLE_API_PENDING';
export const GET_ROLE_API_SUCCESS = 'GET_ROLE_API_SUCCESS';
export const GET_ROLE_API_ERROR = 'GET_ROLE_API_ERROR';
export const GET_ROLE_RESET = 'GET_ROLE_RESET';

export const GET_MYACCOUNT_API_PENDING = 'GET_MYACCOUNT_API_PENDING';
export const GET_MYACCOUNT_API_SUCCESS = 'GET_MYACCOUNT_API_SUCCESS';
export const GET_MYACCOUNT_API_ERROR = 'GET_MYACCOUNT_API_ERROR';
export const GET_MYACCOUNT_RESET = 'GET_MYACCOUNT_RESET';

export const UPDATE_MYACCOUNT_API_PENDING = 'UPDATE_MYACCOUNT_API_PENDING';
export const UPDATE_MYACCOUNT_API_SUCCESS = 'UPDATE_MYACCOUNT_API_SUCCESS';
export const UPDATE_MYACCOUNT_API_ERROR = 'UPDATE_MYACCOUNT_API_ERROR';
export const UPDATE_MYACCOUNT_RESET = 'UPDATE_MYACCOUNT_RESET';

export const CHANGE_PASSWORD_API_PENDING = 'CHANGE_PASSWORD_API_PENDING';
export const CHANGE_PASSWORD_API_SUCCESS = 'CHANGE_PASSWORD_API_SUCCESS';
export const CHANGE_PASSWORD_API_ERROR = 'CHANGE_PASSWORD_API_ERROR';
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET';

export const INVITE_FRIENDS_API_PENDING = 'INVITE_FRIENDS_API_PENDING';
export const INVITE_FRIENDS_API_SUCCESS = 'INVITE_FRIENDS_API_SUCCESS';
export const INVITE_FRIENDS_API_ERROR = 'INVITE_FRIENDS_API_ERROR';